apiVersion: v1
kind: Service
metadata:
  name: svc-service-a
  namespace: test
  labels:
    app: test
spec:
  ports:
  - port: 8080
#    targetPort: 8080
    name: http
  selector:
    app: service-a
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-a
  namespace: test
  labels:
    app: test
  annotations:
    readiness.status.sidecar.istio.io/applicationPorts: "8080"
data:
  config.json: | 
    {
      "IPAddress": "127.0.0.1",
      "Port": "8080",
      "Pages": [ {
                    "Path":"*", 
                    "Status": 200, 
                    "Body": "service-a invoking --> ",
                    "ServiceEndpoints":["http://svc-echo-service-a.test.svc.cluster.local:8080"]
      } ]
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-a
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-a
        version: v1
      annotations:
        status.sidecar.istio.io/port: "0"  # https://github.com/istio/istio/issues/9504
        readiness.status.sidecar.istio.io/applicationPorts: "8080"
    spec:
      containers:
      - name: service-a
        image: khurlbut/fakeserver:v1
        imagePullPolicy: Always #IfNotPresent
        command:
        - fakeserver
        - --config-file=/config/config.json
        - --html=true
        volumeMounts:
          - name: config
            mountPath: /config
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: "config-service-a"   