apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: jwt-policy-test
  namespace: test
spec:
  targets:
  - name: svc-echo-service-a
#  - name: svc-service-b
#  - name: svc-service-c
#  - name: svc-service-d
  peers:
#  - mtls: {}
  origins:
  - jwt:
      issuer: https://stage.api.gap.com/commerce/credentials/token # should issuer really include /token?
      jwks_uri: https://stage.api.gap.com/istio-auth/certs # TODO: move the JWKS endpoint to /credentials, also rename to correct .well-known definition
      # TODO: check if the aud claim is honored automatically
#      audiences:
#      jwt_headers:
  principalBinding: USE_ORIGIN
